Antoinette/swipe all
cuappdev/eatery-blue-ios pull request #16
Opened 2023-04-16 14:28 UTC by antoinztte

## Overview

- applied push EateryPageVC to list of eateries

## Changes Made

- modified pushViewController method to push EateryPageVC instead of HomeModel
- modified DidSelectRowAt

## Test Coverage

- tested on iPhone 14 all sizes

## Next Steps (delete if not applicable)

- fix indexing (based on Jennifer's code once approved) and also figure out how to show all pages at once

## Related PRs or Issues (delete if not applicable)

- Jennifer's recent swipe index PR

2023-04-17 17:35 UTC, ReadeP approved these changes
Looks good! 👍

2023-04-17 17:35 UTC, ReadeP commented on EateryModel/Sources/EateryModel/Networking/SchemaToModel.swift
> +        let df = ISO8601DateFormatter()
rename to `dateFormatter`

2023-04-18 05:57 UTC, jjennifergu requested changes

2023-04-18 05:57 UTC, jjennifergu commented on Eatery Blue/Eatery Blue/UI/HomeScreen/HomeViewController.swift
> +            allEateries.append(eatery)
if you append each eatery in `didSelectRowAt`, the order of the eateries in `allEateries` will be in the order you click on them, which will not be the order of the eateries on the screen. also, you will only be able to scroll through the eateries you have previously clicked on, which is not what we want in this case. I would suggest getting `allEateries` from `HomeModelController`, where the data is fetched from backend

2023-04-18 05:57 UTC, jjennifergu commented on EateryModel/Sources/EateryModel/Networking/EateryAPI.swift
> +//        if let error = schemaApiResponse.error {
this is addressed in my branch that I have already merged, i can help you resolve merge conflicts when you merge this branch. nothing needs to be done here for now

2023-04-18 05:57 UTC, jjennifergu commented on EateryModel/Sources/EateryModel/Networking/Schema.swift
> +//        internal let error: String?
same as above, will help you address when you merge

2023-04-18 05:57 UTC, jjennifergu commented on EateryModel/Sources/EateryModel/Networking/Schema.swift
> +//        internal let canonicalDate: String
same as above

2023-04-26 01:55 UTC, closed without merging