Charles/remove carousel
cuappdev/eatery-blue-ios pull request #174
Opened 2024-10-25 04:15 UTC by rs929

## Overview

TODO

## Changes Made

### Change 1

- TODO
- TODO

### Change 2

- TODO
- TODO

## Test Coverage

- TODO

## Next Steps (optional)

TODO

## Related PRs or Issues (optional)

TODO

## Screenshots (optional)

<details>
  <summary>TODO</summary>
  <table>
    <tr>
      <td>Before</td>
      <td>After</td>
    </tr>
  <tr>
    <td><video src="enterurlhere" type="video/mp4"></td>
    <td><video src="enterurlhere" type="video/mp4"></td>
  </tr>
 </table>
</details>

<details>
  <summary>TODO</summary>
  <table>
    <tr>
      <td>Before</td>
      <td>After</td>
    </tr>
  <tr>
    <td><img src="enterurlhere" width="300px" height="auto"></td>
    <td><img src="enterurlhere" width="300px" height="auto"></td>
  </tr>
 </table>
</details>

<details>
  <summary>TODO</summary>
  <img src="enterurlhere" width="300px" height="auto">
  <video src="enterurlhere" type="video/mp4">
</details>

2024-10-25 16:29 UTC, MrPeterss requested changes
@Xhether nice work, Charles! Overall really clean pr. Just make sure to fix some of the styling changes that I mentioned. In general, we want to put new lines at the beginning and end of classes (after the first curly bracket, and before the last curly bracket). Also, whenever you are using brackets in your logic (for if statements, completion handlers, etc), we want to put new lines after that to break it up (this includes after guard statements).

2024-10-25 16:29 UTC, MrPeterss commented on Eatery Blue/UI/EateryCard/EateryLargeCardContentView.swift
> +
extra new line?

2024-10-25 16:29 UTC, MrPeterss commented on Eatery Blue/UI/EateryCard/EateryLargeCardContentView.swift
> +
extra newline?

2024-10-25 16:29 UTC, MrPeterss commented on Eatery Blue/UI/EateryCard/EateryLargeCardContentView.swift
> +
one of these has to be extra

2024-10-25 16:29 UTC, MrPeterss commented on Eatery Blue/UI/EateryCard/EateryLargeCardContentView.swift
> +//        subtitleLabels[1].attributedText = EateryFormatter.default.eateryCardFormatter(eatery, date: Date())
lets just remove this

2024-10-25 16:29 UTC, MrPeterss commented on Eatery Blue/UI/HomeScreen/HomeModelController.swift
> +
extra tab

2024-10-25 16:29 UTC, MrPeterss commented on Eatery Blue/UI/HomeScreen/HomeModelController.swift
> +
extra newline

2024-10-25 16:29 UTC, MrPeterss commented on Eatery Blue/UI/HomeScreen/HomeModelController.swift
> -
this line should be here

2024-10-25 16:29 UTC, MrPeterss commented on Eatery Blue/main.swift
> -
put this line back too

2024-10-25 16:29 UTC, MrPeterss commented on Eatery Blue/UI/Carousel/CarouselMoreEateriesCollectionViewCell.swift
> -
put this line back

2024-10-25 16:29 UTC, MrPeterss commented on Eatery Blue/UI/HomeScreen/HomeModelController.swift
> +                guard let dist2 else { return true }
New line should go after the guard. Also, I believe lines 216 and 217 can be condensed to:
`guard let dist1, let dist2 else { return true }`

2024-11-18 17:51 UTC, MrPeterss approved these changes
Nice work!

2024-11-18 22:30 UTC, Xhether approved these changes
yippee

2024-11-18 22:30 UTC, merged