Charles/update filters
cuappdev/eatery-blue-ios pull request #176
Opened 2024-10-25 05:56 UTC by Xhether

## Overview

Finished Swap Filter Replacement 

## Changes Made

### Change 1

- Added BRB's filter
- Added MealSwipes filter

### Change 2

- Removed payment methods filter
- Preserved respective order described in original task ( north, west, central, swipes, brbs, favorites, under 10 min )

## Test Coverage

- Compared results with filtering by brbs and mealswipes respectively from the main branch and my branch, which yielded the same expected results

## Next Steps (optional)

N/A

## Related PRs or Issues (optional)

N/a

## Screenshots (optional)

<details>
  <summary>TODO</summary>
  <table>
    <tr>
      <td>Before</td>
      <td>After</td>
    </tr>
  <tr>
    <td><video src="enterurlhere" type="video/mp4"></td>
    <td><video src="enterurlhere" type="video/mp4"></td>
  </tr>
 </table>
</details>

<details>
  <summary>TODO</summary>
  <table>
    <tr>
      <td>Before
</td>
      <td>After</td>
    </tr>
  <tr>
    <td><img src="enterurlhere" width="300px" height="auto"></td>
    <td><img src="enterurlhere" width="300px" height="auto"></td>
  </tr>
 </table>
</details>

<details>
  <summary>TODO</summary>
  <img src="enterurlhere" width="300px" height="auto">
  <video src="enterurlhere" type="video/mp4">
</details>

2024-10-25 16:32 UTC, MrPeterss commented
Make sure to give your pr a relevant title!

2024-10-25 16:43 UTC, MrPeterss requested changes
Nice work getting this out quick charles! However, there seems to be a bug where the "Meal Swipes" filter overrides the "BRB" one when they are both selected. You should decide with Thomas/designers if you want to override one of the filters when the other is selected. If this is the case, then you should visually show this by unselecting the filters. I had to do this for Compare Menus, and made a subclass of the EateryFilterViewController called CompareMenusFilterViewController. The other option is you can compound the two filters together (which would show eateries that accept brbs and meal swipes). Some of the other filters do this, so take a look at that!

2024-10-27 19:10 UTC, rs929 approved these changes
Just a few small styling changes, Make sure to address Peter's changes!

Great PR!

2024-10-27 19:10 UTC, rs929 commented on Eatery Blue/UI/EateryFilter/EateryFilterViewController.swift
> +
Remove this Line

2024-10-27 19:10 UTC, rs929 commented on Eatery Blue/UI/EateryFilter/EateryFilterViewController.swift
> +            delegate?.eateryFilterViewController(self, filterDidChange: filter)
Add newline here

2024-10-27 19:10 UTC, rs929 commented on Eatery Blue/UI/EateryFilter/EateryFilterViewController.swift
> +            delegate?.eateryFilterViewController(self, filterDidChange: filter)
add newline here

2024-11-06 18:08 UTC, Xhether commented
I fixed the filter bug

2024-11-06 19:33 UTC, MrPeterss approved these changes
Nice work! I'll show you how to resolve the merge conflict in work session! Wait to merge until then

2024-11-17 20:41 UTC, merged