Fix loading times
cuappdev/eatery-blue-ios pull request #46
Opened 2023-09-29 20:23 UTC by vinnie4k

## Overview
Fixed the long loading times at first launch.

## Changes Made
- Used the “simple” endpoint to fetch eateries for the home page.
    - Because this endpoint returns less data, the response time is significantly quicker.
- Both endpoints are ran asynchronously on a background thread at the same time. When each endpoint is finished, the UI gets updated automatically.
- There are two cases that we need to handle:
    1. The user waits long enough that wen they tap on the Eatery cell, all menus from the longer endpoint are already loaded in.
    2. The user immediately clicks on the Eatery cell when the longer endpoint has not finished. In this case, the `EateryPageViewController` gets automatically updated as soon as the longer endpoint is finished.
- Additionally, these Eateries are sorted with opened at the very top. If both eateries have the same status, then it is by name descending.

## Test Coverage
- Tested many different cases as mentioned above that the user could do.
- Used print statements to confirm that both endpoints are ran at the exact same time and to see if one of the endpoint has finished before the other.

## Next Steps
- Create a spinner and disable scrolling/interaction in the `EateryPageViewController` when the menus haven’t fully loaded in yet.
    - When they are loaded in, stop the spinner and enable scrolling. Make sure that the menus are smoothly animated into the view instead of immediately popping up.
    - Instead of a basic spinner, we can also do something unique to Eatery, perhaps the spinning Eatery icon or something.
- We will also need to remove the endpoints from our codebase because this is a huge security concern.

## Screenshots

### Case 1
https://github.com/cuappdev/eatery-blue-ios/assets/75594943/c3217237-2afd-4fff-9038-4d2177c92a24

### Case 2
https://github.com/cuappdev/eatery-blue-ios/assets/75594943/41e17905-a4f3-449a-ae8a-3b27caebd266

2023-09-30 22:14 UTC, JaysonHahn requested changes
If for some reason updateAllEateriesFromNetworking() finishes before updateSimpleEateriesFromNetworking() all the menu data will be wiped. I tested that this is the case. I don't know how possible this is but this could cause bugs

2023-09-30 22:56 UTC, vinnie4k commented
@JaysonHahn Good catch. Yea it would be almost impossible. What you can do is prevent the shorter call from updating the eateries if the longer one finished before. A simple boolean can do the trick. Can you do this for me LOL? Just commit directly to this branch.

2023-10-01 00:25 UTC, tiffany-pann approved these changes
Looks good to me and I agree about adding some sort of animation for case 2. In addition, is it the same behavior if you click into an Eatery cell before `updateAllEateriesFromNetworking()` is finished, and then swipe left/right to a different Eatery's pageVC?

2023-10-01 13:58 UTC, JaysonHahn approved these changes
Ok I handled the potential error

2023-10-06 21:57 UTC, closed without merging