Fix load times and load each eatery individually
cuappdev/eatery-blue-ios pull request #48
Opened 2023-10-04 22:14 UTC by JaysonHahn

## Overview

Fix load times and load each eatery individually

## Changes Made

- Used the “simple” endpoint to fetch eateries for the home page.
     Because this endpoint returns less data, the response time is significantly quicker.
- Additionally, these Eateries are sorted with opened at the very top. If both eateries have the same status, then it is by name descending.
- Created functions `loadEatery` and `eatery` that loads in an individual eatery
     This function will be called indivdually for each eatery the first time it is swiped to in the pageviewController
- Added functions `addSpinner` and `deleteSpinner` which adds a spinner as the network request is fetching the eatery
- For each `EateryViewController`  its set up function is called making a fast push and then `setUpMenu` is called for menu data

## Test Coverage

- Used manual testing and used sleep function to verify that the spinner works as intended
- Used print statements to ensure the eateries load with correct data

## Next Steps (delete if not applicable)

- Set up a working cache that saves data both between opening and closing the app and closing the pageview and reopening it.

## Screenshots (delete if not applicable)

<details>

  <summary>Screen Shot Name</summary>

Fast load time 
  
  

https://github.com/cuappdev/eatery-blue-ios/assets/46629787/a80e00e4-5dc0-4648-ae10-d099465d6eb1

</details>

2023-10-05 03:59 UTC, vinnie4k requested changes
Very good work Jayson!!! Please address my comments and request me again. Your PR descriptions are also getting better too!

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/Networking/Networking.swift
> +        let url = URL(string: "\(self.baseUrl)\(id)/")!
I would use an if let here.

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryModelController.swift
> +    var menuHasLoaded = false
```suggestion
    var menuHasLoaded: Bool = false
```
Just to keep it consistent.

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryModelController.swift
> +                delateSpinner()
Typo? "deleteSpinner()"

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryPageViewController.swift
> +        if let page = pages[index] as? EateryModelController{
```suggestion
        if let page = pages[index] as? EateryModelController {
```
Missing a space before the {

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryPageViewController.swift
> +    func pageViewController(
Add a new line above.

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryPageViewController.swift
> +        }
Add a new line below.

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryPageViewController.swift
> +            let index = pages.firstIndex(of: selectedController),
Indent the `let` so that it aligns with the line above.

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryPageViewController.swift
> +            let viewController = selectedController as? EateryModelController {
Indent the `let` so that it aligns with the line above.

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/Networking/Networking.swift
> +    let baseUrl: URL
Usually these should be sorted alphabetically, but if it isn't in the rest of the codebase then it's fine.

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryViewController.swift
>      var categoryViews: [MenuCategoryView] = []
Usually these should be sorted alphabetically, but if it isn't in the rest of the codebase then it's fine.

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryViewController.swift
> +    func delateSpinner() {
Typo. `deleteSpinner()`

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryViewController.swift
> +        spinner.startAnimating()
```suggestion
        spinner.hidesWhenStopped = true
        spinner.startAnimating()
        
        spinner.translatesAutoresizingMaskIntoConstraints = false
        view.addSubview(spinner)
        
        spinner.snp.makeConstraints { make in
            make.top.equalTo(stackView.snp.bottom).offset(10)
            make.width.height.equalTo(stackView.snp.width).multipliedBy(0.25)
            make.centerX.equalTo(stackView.snp.centerX)
        }
```

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/HomeScreen/HomeModelController.swift
> -    }
Fix the indentation.

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/HomeScreen/HomeModelController.swift
> +                if isLoading{
```suggestion
                if isLoading {
```

2023-10-05 03:59 UTC, vinnie4k commented on EateryModel/Sources/EateryModel/Networking/EateryAPI.swift
> +        }
```suggestion
        do {
            schemaApiResponse = try decoder.decode(Schema.Eatery.self, from: data)
        } catch {
            throw EateryAPIError.apiResponseError(error.localizedDescription)
        }
```

2023-10-05 03:59 UTC, vinnie4k commented on Eatery Blue/UI/HomeScreen/HomeModelController.swift
> +                        return $0.isOpen
Lowkey you could do `$0.isOpen == $1.isOpen ? ($0.name < $1.name) : $0.isOpen`
Not sure if that will work though

2023-10-07 01:40 UTC, vinnie4k approved these changes
Just fix those 2 comments (very short) and you should be good to go.

2023-10-07 01:40 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryPageViewController.swift
> +
Remove extra line.

2023-10-07 01:40 UTC, vinnie4k commented on Eatery Blue/UI/EateryScreen/EateryViewController.swift
> +        spinner.translatesAutoresizingMaskIntoConstraints = false
Don't need `translatesAutoresizingMaskIntoConstraints` when using SnapKit.

2023-10-09 04:22 UTC, antoinztte approved these changes
Good to go.

2023-10-09 04:42 UTC, merged